site_name: Docs
site_url: https://ankojubhanuprakash.github.io/
markdown_extensions:
        - extra
        - tables
        - mdx_math:
            enable_dollar_delimiter: True
        - fenced_code
    #theme: readthedocs
extra_javascript: 
        - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#nav: 
#  - Home : 
#  - Projects : 
#  - NLP : 
#  - RL :

